default_platform(:ios)

platform :ios do
  desc "Create PR with release changes"
  lane :make_pull_request do |options|
    version = options[:version]
    dry_run = options[:dry_run] || false
    github_token = options[:github_token] || ENV["GITHUB_TOKEN"]
    release_branch = options[:release_branch] || "main"

    if version.nil?
      version = get_next_release_version()
      puts("version is: #{version}!")
    end

    update_changelog(version: version)
    update_version(version: version)

    create_github_pull_request(
      version: version,
      release_branch: release_branch,
      github_token: github_token
    )
  end

  desc "Create new release on github"
  lane :make_release do |options|
    dry_run = options[:dry_run] || false
    github_token = options[:github_token] || ENV["GITHUB_TOKEN"]
    release_branch = options[:release_branch] || "main"

    version = get_next_release_version()
    release_notes = get_release_notes(version: version)

    create_github_release(
      version: version,
      release_notes: release_notes,
      github_token: github_token,
      release_branch: release_branch,
      dry_run: dry_run
    )
  end

  desc "Create new release on github"
  lane :make_publish_pods do |options|
    dry_run = options[:dry_run] || false
    github_token = options[:github_token] || ENV["GITHUB_TOKEN"]
    release_branch = options[:release_branch] || "main"

    version = get_next_release_version()
    release_notes = get_release_notes(version: version)

    create_github_release(
      version: version,
      release_notes: release_notes,
      github_token: github_token,
      release_branch: release_branch,
      dry_run: dry_run
    )
  end

##############################################################################
# RELEASE
##############################################################################

  desc "Create release on GitHub"
  private_lane :create_github_release do |options|
    version = options[:version]
    version_tag = "v#{version}"
    release_notes = options[:release_notes]
    github_token = options[:github_token]
    release_branch = options[:release_branch]
    dry_run = options[:dry_run] 

    if dry_run == true
      UI.important("Running in \"dry run\" mode. Release won't be published.")
    else
      if github_token.nil?
        UI.user_error!("GitHub Token is required to make release.")
      end

      set_github_release(
      repository_name: "arjankowski/github-actions-release-test",
      api_token: github_token,
      name: version_tag,
      tag_name: version_tag,
      description: release_notes,
      commitish: release_branch
    )
    end
  end

  desc "Commit version update"
  private_lane :create_github_pull_request do |options|
    version = options[:version]
    github_token = options[:github_token]
    release_branch = options[:release_branch]
    commit_version_tag = "v#{version}"
    commit_title = "chore: release #{commit_version_tag}"

    puts("*#{commit_version_tag}*")

    Dir.chdir("..") do
      sh("git checkout -b #{commit_version_tag}")
      sh("git add .")
      sh("git commit -am \"#{commit_title}\"")
      sh("git push origin #{commit_version_tag}")

    create_pull_request(
      api_token: github_token,
      repo: "arjankowski/github-actions-release-test",
      title: "#{commit_title}",
      head: "#{commit_version_tag}",
      base: "#{release_branch}",
    )
    end
  end


  ##############################################################################
  # VERSION UPDATE
  ##############################################################################

  desc "Get next release version based on conventional commits"
  private_lane :get_next_release_version do |options|
    release_version = ""
    Dir.chdir("..") do
      release_version = sh("standard-version --dry-run |  sed -En \"s/.*tagging release v(.*)/\\1/p\" | tr -d \"\n\"")
    end

    release_version
  end

  desc "Validate version"
  private_lane :is_version_valid do |options|
    version = options[:version]
    !!(version =~ /^\d+\.\d+\.\d+$/)
  end

  desc "Update SDK version"
  private_lane :update_version do |options|
    version = options[:version]


    # Update BoxSDK.podspec
    podspec_path = ENV["PODSPEC_PATH"]
    sh("sed -i.bak -E 's|(.*s.version.* = ).*|\\1\"#{version}\"|g' #{podspec_path}")
    sh("rm #{podspec_path}.bak")
  
  end

##############################################################################
# CHANGELOG UPDATE
##############################################################################

desc "Return release notes based on conventional commits"
private_lane :get_release_notes do |options|
  version = options[:version]
  escaped_version = sh("echo \"#{version}\" | sed -E 's/(\\.)/\\\\\\./g' | tr -d \"\n\"")
  release_notes = ""
  
  Dir.chdir("..") do
    release_notes = sh("sed -nE '/^## \\[#{escaped_version}\\]/,/^## \\[[0-9]+\.[0-9]+\.[0-9]+\\]/p' CHANGELOG.md | sed '1,2d' | sed '$d'")
  end
  
  release_notes
end

  # desc "Return release notes based on actual CHANGELOG.md file"
  # private_lane :get_release_notes do |options|
  #   changelog_path = ENV["CHANGELOG_PATH"]
  #   release_notes_to_process = sh("sed -nE '/^## Next/,/^## v/p'  #{changelog_path} | sed -e '$ d' | sed 1,2d")

  #   processing_section = ""
  #   final_release_notes = ""
  #   release_notes_to_process.each_line do |line|
  #     if ["__Breaking Changes:__\n", "__New Features and Enhancements:__\n", "__Bug Fixes:__\n"].include? line
  #       if processing_section.lines.count > 2
  #         final_release_notes += processing_section 
  #       end

  #       processing_section = ""
  #     end
  #     processing_section += line
  #   end

  #   if processing_section.lines.count > 2
  #     final_release_notes += processing_section 
  #   end

  #   final_release_notes
  # end

  desc "Update CHANGELOG.md file based on conventional commits"
  private_lane :update_changelog do |options|
    version = options[:version]

    Dir.chdir("..") do
      sh("standard-version --skip.tag --skip.commit --release-as #{version}")
    end
  end
  
  # desc "Update changelog"
  # private_lane :update_changelog do |options|
  #   version = options[:version]
  #   release_notes = options[:release_notes]
  #   changelog_path = ENV["CHANGELOG_PATH"]
  #   date = sh("date '+%Y-%m-%d' | tr -d '\n'")

  #   # Remove empty sections from "Next Release"
  #   sh("sed -i '.bak' -E '/^## Next/,/^## v/{//!d;}' #{changelog_path}")
  #   File.open(changelog_path, "r+") do |file|
  #     content = ""``
  #     line_number = 1
  #     file.each_line do |file_line|
  #     if line_number == 5
  #       content += "\n"
  #       release_notes.lines.each { |notes_line|
  #         content += notes_line
  #       }
  #     end

  #     content += file_line
  #     line_number += 1
  #     end

  #     file.rewind
  #     file.write(content)
  #   end

  #   # Change Next Release to specific version
  #   sh("sed -i.bak -E 's/## Next Release.*/## v#{version} \[#{date}\]/g' #{changelog_path}")
  #   sh("rm #{changelog_path}.bak")

  #   # Add next release template
  #   header_template = ENV["CHANGELOG_HEADER_TEMPTLATE"].split("\n")
  #   header_template.reverse.each { |line| 
  #     sh("sed -i '.bak' '4s/^/#{line}\\n\\n/' #{changelog_path}")
  #   }
  #   sh("rm #{changelog_path}.bak")
  #   end
end
